/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Class.DatabaseConnection;
import Class.Login;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SMKN4
 */
public class ReportSuratMasuk extends javax.swing.JFrame {

    /**
     * Creates new form ReportSuratMasuk
     */
    Connection koneksi;

    public ReportSuratMasuk() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi = DatabaseConnection.bukaKoneksi("localhost", "3306", "root", "", "db_arsip_surat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        Tittle6 = new javax.swing.JLabel();
        btnHome5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnSuratMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnSMdata = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnSuratKeluar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSKnew = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnLapSM = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnLapSk = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnLapDisposisi = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnGantiPassword = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        btnHelp = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnClose2 = new javax.swing.JPanel();
        Tittle4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        dateAwal = new com.toedter.calendar.JDateChooser();
        dateAkhir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel10.setBackground(new java.awt.Color(21, 21, 21));

        Tittle6.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        Tittle6.setForeground(new java.awt.Color(255, 255, 255));
        Tittle6.setText("Bird Mail");

        btnHome5.setBackground(new java.awt.Color(21, 21, 21));
        btnHome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHome5MousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jLabel19.setText("Home");

        javax.swing.GroupLayout btnHome5Layout = new javax.swing.GroupLayout(btnHome5);
        btnHome5.setLayout(btnHome5Layout);
        btnHome5Layout.setHorizontalGroup(
            btnHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHome5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHome5Layout.setVerticalGroup(
            btnHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnSuratMasuk.setBackground(new java.awt.Color(21, 21, 21));
        btnSuratMasuk.setPreferredSize(new java.awt.Dimension(75, 24));
        btnSuratMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuratMasukMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Surat Masuk.png"))); // NOI18N
        jLabel7.setText("Incoming Mail");

        javax.swing.GroupLayout btnSuratMasukLayout = new javax.swing.GroupLayout(btnSuratMasuk);
        btnSuratMasuk.setLayout(btnSuratMasukLayout);
        btnSuratMasukLayout.setHorizontalGroup(
            btnSuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSuratMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSuratMasukLayout.setVerticalGroup(
            btnSuratMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnSMdata.setBackground(new java.awt.Color(21, 21, 21));
        btnSMdata.setPreferredSize(new java.awt.Dimension(75, 24));
        btnSMdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSMdataMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data Surat.png"))); // NOI18N
        jLabel9.setText("Incoming Mail Data");

        javax.swing.GroupLayout btnSMdataLayout = new javax.swing.GroupLayout(btnSMdata);
        btnSMdata.setLayout(btnSMdataLayout);
        btnSMdataLayout.setHorizontalGroup(
            btnSMdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSMdataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSMdataLayout.setVerticalGroup(
            btnSMdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnSuratKeluar.setBackground(new java.awt.Color(21, 21, 21));
        btnSuratKeluar.setPreferredSize(new java.awt.Dimension(75, 24));
        btnSuratKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuratKeluarMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Surat Keluar.png"))); // NOI18N
        jLabel10.setText("Outgoing Mail");

        javax.swing.GroupLayout btnSuratKeluarLayout = new javax.swing.GroupLayout(btnSuratKeluar);
        btnSuratKeluar.setLayout(btnSuratKeluarLayout);
        btnSuratKeluarLayout.setHorizontalGroup(
            btnSuratKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSuratKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSuratKeluarLayout.setVerticalGroup(
            btnSuratKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnSKnew.setBackground(new java.awt.Color(21, 21, 21));
        btnSKnew.setPreferredSize(new java.awt.Dimension(75, 24));
        btnSKnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSKnewMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Data Surat.png"))); // NOI18N
        jLabel11.setText("Outgoing Mail");

        javax.swing.GroupLayout btnSKnewLayout = new javax.swing.GroupLayout(btnSKnew);
        btnSKnew.setLayout(btnSKnewLayout);
        btnSKnewLayout.setHorizontalGroup(
            btnSKnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSKnewLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSKnewLayout.setVerticalGroup(
            btnSKnewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnLaporan.setBackground(new java.awt.Color(21, 21, 21));
        btnLaporan.setPreferredSize(new java.awt.Dimension(75, 24));
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLaporanMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Laporan.png"))); // NOI18N
        jLabel13.setText("Report");

        javax.swing.GroupLayout btnLaporanLayout = new javax.swing.GroupLayout(btnLaporan);
        btnLaporan.setLayout(btnLaporanLayout);
        btnLaporanLayout.setHorizontalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLaporanLayout.setVerticalGroup(
            btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnLapSM.setBackground(new java.awt.Color(21, 21, 21));
        btnLapSM.setPreferredSize(new java.awt.Dimension(75, 24));
        btnLapSM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLapSMMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Surat Masuk.png"))); // NOI18N
        jLabel14.setText("Incoming Mail");

        javax.swing.GroupLayout btnLapSMLayout = new javax.swing.GroupLayout(btnLapSM);
        btnLapSM.setLayout(btnLapSMLayout);
        btnLapSMLayout.setHorizontalGroup(
            btnLapSMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLapSMLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLapSMLayout.setVerticalGroup(
            btnLapSMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnLapSk.setBackground(new java.awt.Color(21, 21, 21));
        btnLapSk.setPreferredSize(new java.awt.Dimension(75, 24));
        btnLapSk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLapSkMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Surat Keluar.png"))); // NOI18N
        jLabel15.setText("Outgoing Mail");

        javax.swing.GroupLayout btnLapSkLayout = new javax.swing.GroupLayout(btnLapSk);
        btnLapSk.setLayout(btnLapSkLayout);
        btnLapSkLayout.setHorizontalGroup(
            btnLapSkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLapSkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLapSkLayout.setVerticalGroup(
            btnLapSkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnLapDisposisi.setBackground(new java.awt.Color(21, 21, 21));
        btnLapDisposisi.setPreferredSize(new java.awt.Dimension(75, 24));
        btnLapDisposisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLapDisposisiMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Disposisi.png"))); // NOI18N
        jLabel16.setText("Disposition");

        javax.swing.GroupLayout btnLapDisposisiLayout = new javax.swing.GroupLayout(btnLapDisposisi);
        btnLapDisposisi.setLayout(btnLapDisposisiLayout);
        btnLapDisposisiLayout.setHorizontalGroup(
            btnLapDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLapDisposisiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLapDisposisiLayout.setVerticalGroup(
            btnLapDisposisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnSettings.setBackground(new java.awt.Color(21, 21, 21));
        btnSettings.setPreferredSize(new java.awt.Dimension(75, 24));
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSettingsMousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Setting.png"))); // NOI18N
        jLabel28.setText("Settings");

        javax.swing.GroupLayout btnSettingsLayout = new javax.swing.GroupLayout(btnSettings);
        btnSettings.setLayout(btnSettingsLayout);
        btnSettingsLayout.setHorizontalGroup(
            btnSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSettingsLayout.setVerticalGroup(
            btnSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnGantiPassword.setBackground(new java.awt.Color(21, 21, 21));
        btnGantiPassword.setPreferredSize(new java.awt.Dimension(75, 24));
        btnGantiPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGantiPasswordMousePressed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profile.png"))); // NOI18N
        jLabel42.setText("Profile");

        javax.swing.GroupLayout btnGantiPasswordLayout = new javax.swing.GroupLayout(btnGantiPassword);
        btnGantiPassword.setLayout(btnGantiPasswordLayout);
        btnGantiPasswordLayout.setHorizontalGroup(
            btnGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGantiPasswordLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGantiPasswordLayout.setVerticalGroup(
            btnGantiPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGantiPasswordLayout.createSequentialGroup()
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHelp.setBackground(new java.awt.Color(21, 21, 21));
        btnHelp.setPreferredSize(new java.awt.Dimension(75, 24));
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHelpMousePressed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        jLabel44.setText("Help");

        javax.swing.GroupLayout btnHelpLayout = new javax.swing.GroupLayout(btnHelp);
        btnHelp.setLayout(btnHelpLayout);
        btnHelpLayout.setHorizontalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHelpLayout.setVerticalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(21, 21, 21));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logout.png"))); // NOI18N
        jLabel45.setText("Logout");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel45)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSuratMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(btnSuratKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(btnHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(btnSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGantiPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSKnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btnSMdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Tittle6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnLapSM, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btnLapSk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btnLapDisposisi, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tittle6)
                .addGap(18, 18, 18)
                .addComponent(btnHome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSMdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuratKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSKnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLapSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLapSk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLapDisposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGantiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnClose2.setBackground(new java.awt.Color(153, 153, 153));

        Tittle4.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        Tittle4.setText("X");
        Tittle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tittle4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnClose2Layout = new javax.swing.GroupLayout(btnClose2);
        btnClose2.setLayout(btnClose2Layout);
        btnClose2Layout.setHorizontalGroup(
            btnClose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClose2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(Tittle4)
                .addContainerGap())
        );
        btnClose2Layout.setVerticalGroup(
            btnClose2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tittle4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("Report Surat Masuk");

        jLabel17.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(66, 66, 66));
        jLabel17.setText("Dari Tanggal");

        jLabel18.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(66, 66, 66));
        jLabel18.setText("Sampai Dengan Tanggal");

        btnSubmit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSubmit.setText("Print");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnSubmit)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubmit)
                            .addComponent(dateAkhir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tittle4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tittle4MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Tittle4MousePressed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;

        try {
            String TanggalLahir = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(TanggalLahir);

            HashMap parameter = new HashMap();
            parameter.put("tgl", dateAwal.getDate());
            parameter.put("tgl2", dateAkhir.getDate());

            reportSource = System.getProperty("user.dir") + "/Report/ReportSuratMasuk.jrxml";
            reportDest = System.getProperty("user.dir") + "/Report/ReportSuratMasuk.jasper";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnHome5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome5MousePressed
        // TODO add your handling code here:
        HomeUser l = new HomeUser();
        l.show();
        dispose();
    }//GEN-LAST:event_btnHome5MousePressed

    private void btnSuratMasukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuratMasukMousePressed
        // TODO add your handling code here:
        SuratMasuk l = new SuratMasuk();
        l.show();
        dispose();
    }//GEN-LAST:event_btnSuratMasukMousePressed

    private void btnSMdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMdataMousePressed
        // TODO add your handling code here:
        SuratMasukData l = new SuratMasukData();
        l.show();
        dispose();
    }//GEN-LAST:event_btnSMdataMousePressed

    private void btnSuratKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuratKeluarMousePressed
        // TODO add your handling code here:
        SuratKeluar l = new SuratKeluar();
        l.show();
        dispose();
    }//GEN-LAST:event_btnSuratKeluarMousePressed

    private void btnSKnewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSKnewMousePressed
        // TODO add your handling code here:
        SuratKeluarData l = new SuratKeluarData();
        l.show();
        dispose();
    }//GEN-LAST:event_btnSKnewMousePressed

    private void btnLaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMousePressed
        // TODO add your handling code here:
        Laporan l = new Laporan();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLaporanMousePressed

    private void btnLapSMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapSMMousePressed
        // TODO add your handling code here:
        ReportSuratMasuk l = new ReportSuratMasuk();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLapSMMousePressed

    private void btnLapSkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapSkMousePressed
        // TODO add your handling code here:
        ReportSuratKeluar l = new ReportSuratKeluar();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLapSkMousePressed

    private void btnLapDisposisiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDisposisiMousePressed
        // TODO add your handling code here:
        ReportDisposisi l = new ReportDisposisi();
        l.show();
        dispose();
    }//GEN-LAST:event_btnLapDisposisiMousePressed

    private void btnSettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMousePressed
        // TODO add your handling code here:
        Settings l = new Settings();
        l.show();
        dispose();
    }//GEN-LAST:event_btnSettingsMousePressed

    private void btnGantiPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGantiPasswordMousePressed
        // TODO add your handling code here:
        Profile l = new Profile();
        l.show();
        dispose();
    }//GEN-LAST:event_btnGantiPasswordMousePressed

    private void btnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMousePressed
        // TODO add your handling code here:
        Help l = new Help();
        l.show();
        dispose();
    }//GEN-LAST:event_btnHelpMousePressed

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_jPanel9MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportSuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportSuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportSuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportSuratMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportSuratMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tittle4;
    private javax.swing.JLabel Tittle6;
    private javax.swing.JPanel btnClose2;
    private javax.swing.JPanel btnGantiPassword;
    private javax.swing.JPanel btnHelp;
    private javax.swing.JPanel btnHome5;
    private javax.swing.JPanel btnLapDisposisi;
    private javax.swing.JPanel btnLapSM;
    private javax.swing.JPanel btnLapSk;
    private javax.swing.JPanel btnLaporan;
    private javax.swing.JPanel btnSKnew;
    private javax.swing.JPanel btnSMdata;
    private javax.swing.JPanel btnSettings;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel btnSuratKeluar;
    private javax.swing.JPanel btnSuratMasuk;
    private com.toedter.calendar.JDateChooser dateAkhir;
    private com.toedter.calendar.JDateChooser dateAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
